language: java

#We build against the latest JDK
jdk:
  - oraclejdk8

#We build at Ubuntu 14.04 (Trusty Tahr) as we want to use a more recent Ubuntu version
sudo: required
dist: trusty

before_install:
  - cd org.eclipse.winery.model.csar.toscametafile
  - mvn install
  - cd ../org.eclipse.winery.model.selfservice
  - mvn install
  - cd ../org.eclipse.winery.model.tosca
  - mvn install
  - cd ..

#We do not need special build commands, as we use the default maven configuration
#For more information see https://docs.travis-ci.com/user/languages/java
