name: Winery CI

on: [ push, pull_request ]

jobs:

  java8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -Pjava -B package

  java12:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 12
        uses: actions/setup-java@v1
        with:
          java-version: 12
      - name: Build with Maven
        run: mvn -Pjava -B package
      - name: Run codacy-coverage-reporter
        if: ${{ github.repository_owner == 'OpenTOSCA' }}
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: org.eclipse.winery.reporting/target/site/jacoco-aggregate/jacoco.xml

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 12
        uses: actions/setup-java@v1
        with:
          java-version: 12
      - name: Build with Maven
        run: mvn -Pfrontend -B package
