# This workflow will build a Java project with Maven
# For more information see: https://blog.oddbit.com/post/2020-09-25-building-multi-architecture-im/
name: Push docker images to Dockerhub

on:
  push:
    branches:
      - master
    tags:
      - "v*.*.*"

jobs:
  dockerBuild:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'OpenTOSCA' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set variables
        id: vars
        run: |
          DOCKER_IMAGE=opentosca/winery
          VERSION=latest
          SHORTREF=${GITHUB_SHA::8}

          # If this is git tag, use the tag name
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
          fi
          TAGS="${DOCKER_IMAGE}:${VERSION},${DOCKER_IMAGE}:${SHORTREF}"

          # Set output parameters.
          echo ::set-output name=tags::${TAGS}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and push latest Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64 #,linux/arm64,linux/arm64/v8
          push: true
          tags: ${{ steps.vars.outputs.tags }}
